before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
language: ruby
rvm:
- 2.3.0
bundler_args: --jobs=2
script:
  - bundle exec rake db:setup
cache: bundler
services:
  - postgresql
addons:
  postgresql: "9.4"